version: '3'
services:
  # postgres:
  #   container_name: database 
  #   image: postgres:latest
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 12345678
  #     POSTGRES_DB: postgres
  # backend:
  #  container_name: backend
  #  build: .
  #  restart: always
  #  ports:
  #    - "8080:8080"  
  #  depends_on:
  #    - postgres  
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
      - MINIO_DEFAULT_BUCKETS=files
  redis:
    image: redis:latest
    container_name: my_redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    # depends_on:
    #   - backend
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

networks:
  minionetwork:
    driver: bridge

volumes:
  redis_data:
    driver: local
  grafana-storage: {}
  minio_data:
    driver: local